### ISSUE TITLE
Incompatible with consolidation/config 2.x

### ISSUE THREAD

**Issue by mikemadison13** [grasmash/yaml-expander#25]
Drush 11.x adds a dependency for consolidation/config 2.x and that package requires grasmash/expander ^2.0.1 but this package still has it locked at ^1. We need to update to ^2 to allow things elsewhere to update.

**Comment by Jelle-S** [comment]
@grasmash Would it be possible to tag a release for this fix please? :)

**Comment by grasmash** [comment]
Yes.
