### ISSUE TITLE
Allow dynamic injection of values

### ISSUE THREAD

**Issue by greg-1-anderson** [grasmash/yaml-expander#9]
In https://github.com/consolidation/config/issues/12, a request was made to allow arbitrary expansion of environment variables within substitutions. This could be done today with code similar to the following:
```
$array = \Symfony\Component\Yaml\Yaml::parse(file_get_contents("dune.yml"));
$reference_properties = ['env' => $_ENV];
$expanded = \Grasmash\YamlExpander\Expander::expandArrayProperties($array, $reference_properties);
```
In the example above, `${env. MY_ARBITRARY_VAR}` would be substituted with the value of the environment variable `MY_ARBITRARY_VAR`.

However, this implementation is undesirable for a couple of reasons. `$_ENV` might not be populated, depending on the active php.ini settings; if `$_ENV` is available, it might be inefficient to copy every environment variable into the reference properties. The caller could copy only specifically named environment variables into the reference properties, but that would be one more thing that would have to be maintained.

Suggestion:

Modify [Expander:: expandProperty()](https://github.com/grasmash/yaml-expander/blob/master/src/Expander.php#L242:L256) to check for dynamic properties when [a value cannot be found](https://github.com/grasmash/yaml-expander/blob/master/src/Expander.php#L246). This point in the execution could be modified to call another routine that would call `getenv()` when the property name begins with `env.`.

This seems generally useful.

**Comment by grayside** [comment]
I am willing to lay down some code on this with a green light for the approach.

**Comment by grasmash** [comment]
Yes I'd accept the code outlined in @greg-1-anderson's proposal.

> Modify Expander:: expandProperty() to check for dynamic properties when a value cannot be found. This point in the execution could be modified to call another routine that would call getenv() when the property name begins with env..
